version: '3.4'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD
      - GTFSDB_PASSWORD
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
  gtfsrdb:
    build:
      context: .
      dockerfile: Dockerfile.gtfsrdb
    image: gtfsrdb
    environment:
      - POSTGRES_PASSWORD
      - GTFSDB_PASSWORD
      - TRIP_UPDATE_URL
      - SERVICE_ALERT_URL
      - VEHICLE_POSITION_URL
      - appID
    command: /usr/local/src/run-gtfsrdb.bash
