version: '3.4'
services:
  gtfs-collector:
    build:
      context: .
      dockerfile: Dockerfile
    image: gtfs-collector
    ports:
      - $HOST_POSTGRES_PORT:5432
    environment:
      - POSTGRES_PASSWORD
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
