#! /bin/bash
#
# Copyright (C) 2016 M. Edward (Ed) Borasky <znmeb@znmeb.net>
# License: MIT

pushd /usr/local/src//gtfsrdb
python ./gtfsrdb.py \
  -t "http://developer.trimet.org/ws/V1/TripUpdate?appID=${appID}" \
  -a "http://developer.trimet.org/ws/V1/FeedSpecAlerts?appID=${appID}" \
  -p "https://developer.trimet.org/ws/gtfs/VehiclePositions?appID=${appID}" \
  -d postgresql://znmeb@localhost:5432/gtfsdb -c
popd
