#! /bin/bash
#
# Copyright (C) 2016 M. Edward (Ed) Borasky <znmeb@znmeb.net>
# License: MIT

source virtualenvwrapper.sh
workon gtfsdb
dropdb gtfsdb
createdb gtfsdb
psql -d gtfsdb -c "CREATE EXTENSION postgis CASCADE;"

pushd ~/Projects/gtfsdb
/usr/bin/time bin/gtfsdb-load \
  --database_url postgresql://znmeb@localhost:5432/gtfsdb --is_geospatial \
  http://developer.trimet.org/schedule/gtfs.zip  
popd
